services:
  api:
    build:
      context: ./url-shortener-api
      dockerfile: Dockerfile.dev
    ports:
      - 5050:5050
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - url-shortner-network
    volumes:
      - ./url-shortener-api:/app
      - /app/node_modules

  ui:
    build:
      context: ./ui/url-shortner
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - url-shortner-network
    volumes:
      - ./ui/url-shortner:/app
      - /app/node_modules

  db:
    image: postgres:17.5-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=url_shortener
    networks:
      - url-shortner-network
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  url-shortner-network:
    driver: bridge

