version: '3'

services:
  api:
    build:
      context: ./url-shortener-api
    ports:
      - 5050:5050
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - brige

  ui:
    build:
      context: ./ui/shortner-ui
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - brige

  db:
    image: postgres:17.5-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - brige
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  brige:
